### ISSUE TITLE
【20161208】CSS line-height 百分比和数值的区别

### ISSUE THREAD

**Issue by zhongxia245** [zhongxia245/One-Day-One-Tip#57]
>时间：2016-12-08 11:44:54

## 一、结论
>line-height: 150%   不等于 line-height: 1.5
line-height的值为百分比: **子集元素继承父级元素的距离**
line-height的值为数值 : **子元素计算各自的行距离**

## 1. line-height 为百分比
```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Document</title>
    <style>
        body{
            font-size:14px;
            line-height:150%;
            background: black;
        }
        p{
            font-size:26px;
            background: gray;
            color: white;
        }
    </style>
</head>
<body>
    <p>你好！</p>
</body>
</html>
```
效果：
![](http://ww4.sinaimg.cn/large/65e4f1e6gw1faj8mmgx85j209001ddfr.jpg)

例子1结果
```less
body{font-size:14px;line-height:150%;}
p{font-size:26px;}

//结果就是：
body{line-height:21px;}//14*150%=21
p{line-heigt:21px;}//继承父元素 
```

### 2. line-height 为数值
```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Document</title>
    <style>
        body{
            font-size:14px;
            line-height:1.5;
            background: black;
        }
        p{
            font-size:26px;
            background: gray;
            color: white;
        }
    </style>
</head>
<body>
    <p>你好！</p>
</body>
</html>
```

**效果：**
![](http://ww2.sinaimg.cn/large/65e4f1e6jw1faj8qek49pj209m01qq2v.jpg)

**说明：**
```less
body{font-size:14px;line-height:1.5;}
p{font-size:26px;}
//结果就是：
body{line-height:21px;} //14*1.5=21 
p{line-height:39px;} //26*1.5=39
```
