### ISSUE TITLE
【20161212】IOS input 内阴影

### ISSUE THREAD

**Issue by zhongxia245** [zhongxia245/One-Day-One-Tip#62]
一个input中在安卓手机上完全按照自己的样式去展示，但是在苹果手机上发现Input有内阴影，怎么去除内阴影呢？

在input样式中这样添加
```css
input {
   appearance: none;
   -moz-appearance: none; /* Firefox */
   -webkit-appearance: none; /* Safari 和 Chrome */
}
```

内阴影效果图：
![](http://ww4.sinaimg.cn/large/006tKfTcgw1fao8x7qqw1j30li0bcgmi.jpg)

去掉后效果：
![](http://ww4.sinaimg.cn/large/006tKfTcjw1fao8ypfqlnj30k40b6js2.jpg)
