### ISSUE TITLE
【20170315】移动端下 Input  placeholder 不垂直居中问题解决方案

### ISSUE THREAD

**Issue by zhongxia245** [zhongxia245/One-Day-One-Tip#82]
PC端chrome设备模拟器里面
![](https://ww3.sinaimg.cn/large/006tNc79ly1fdnp7irxf4j30la0700t5.jpg)

iphone7里面
![](https://ww3.sinaimg.cn/large/006tNc79ly1fdnp7ynlbbj30lm076jru.jpg)

区别
- iphone7 下 placeholder 字体变成12px
- 移动端下，placeholder 不垂直居中

解决方案：
```css
input::-webkit-input-placeholder{
        font-size: 14px ；    //解决iphone下字体大小为12的问题（和input大小不一致）
        line-height: 1em；   //解决不垂直居中的问题
}
```
